#ifndef KLEINANZEIGENDE_GLOBAL_H
#define KLEINANZEIGENDE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KLEINANZEIGENDE_LIBRARY)
#  define KLEINANZEIGENDESHARED_EXPORT Q_DECL_EXPORT
#else
#  define KLEINANZEIGENDESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // KLEINANZEIGENDE_GLOBAL_H
